export const STEAM_GETMATCHHISTORY_SUCCESS = 'STEAM_GETMATCHHISTORY_SUCCESS';
export const STEAM_GETMATCHDETAILS_SUCCESS = 'STEAM_GETMATCHDETAILS_SUCCESS';
export const STEAM_GETPLAYERSSUMMARIES_SUCCESS = 'STEAM_GETPLAYERSSUMMARIES_SUCCESS';
export const OD_GETPLAYER_SUCCESS = 'OD_GETPLAYER_SUCCESS';
